---
# tasks file for common
- name: Creates directory
  win_file:
    path: c:/ravi
    state: directory

- name: copyfiles
  win_copy:
    src: "{{item}}"
    dest: "c:/ravi/"
  loop: "{{files}}"
  notify: copy_message
  
