---
mywin1:
 hosts:
  SRV-Vaibhav:
   ansible_user: administrator
   ansible_password: ntms123#
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5986
   ansible_winrm_server_cert_validation: ignore
   ...